### ISSUE TITLE
Update availability-sets fault count

### ISSUE THREAD

**Issue by chobbs** [influxdata/azure-resource-manager-influxdb-enterprise#15]
Need to update the **PlatformFaultDomainCount** value in the datanodes VM template. Default incorrectly set to 3.

**Comment by lindsve** [comment]
Why is the bug label removed from this issue? I ran into this now when I wanted to try this offering. Any workaround to get Influx set up?

**Comment by chobbs** [comment]
@lindsve were you able to get your deployment running? I imagine this fix should not cause an issue with your deployment ?

**Comment by lindsve** [comment]
@chobbs I got everything deployed after I edited the template for the datanodes and updated the platformFaultDomainCount from 3 to 2 (not that I know what this is, but the error details stated that it should in range 1 to 2), but I'm a bit lost in how to continue.

First, I've used to use a single node InfluxDB instance from the `influxdb` docker image on a inhouse VM. That has been our prototype, but we want to set up something that scales a bit more now that we move our infrastructure to Azure.

I've yet to figure out how to proceed though. When I log on to influx cli with the dbadmin user I created with the deployment template, I'm not able to create a database for our application. It simply says that I need to create an admin user first or disable authentication. I would assume that the dbadmin user created during deployment was suitable.

I did also set up a Chronograf instance, and (after much googling and browsing github) I found the default port and managed to connect to it. I then found the influxdb admin tool within Chronograf and tried to create a database from the web UI. It says that the database was created successfully, but when I switch to Users and back the database is no longer listed.

When I try to create a user within InfluxDB Admin I just get an error message saying the connection was refused.

This is a bit off topic to this github issue, but some guidance in how to set up a database with a dedicated user account after running this deployment would be great and appreciated.

(And I know that we need to enable HTTPS also, but that I have found the documentation for)

**Comment by chobbs** [comment]
thanks for the details @lindsve - we are adding a few updates in the next release to make it easier to get started with Chronograf without additional searching.  The default Db user you define during the deployment should allow you to create databases, users, etc: can you try the following ( if you have external lb you can use that endpoint)

Cmd CREATE DATABASE: 
`curl http://vmdata-0:8086/query -u username:password  --data-urlencode "q=create database test"`

If the above doesn't work you may want to check your credentials 

Also, if you could please submit a support ticket to support@influxdata.com and reference you account number. we can take a look to see if there's something missing from the deployment.

**Comment by lindsve** [comment]
That was a bit more helpful as it gave a error message :)

> {"results":[{"statement_id":0,"error":"meta service unavailable"}]}

Maybe there are things missing from the deployment afterall.

![Skjermbilde 2020-05-28 kl  08 40 28](https://user-images.githubusercontent.com/159861/83107651-edad2800-a0be-11ea-8b3e-7b854667c7ae.png)

But I can follow up via a support ticket

**Comment by lindsve** [comment]
There might be an issue with my selected location (Norway East).

I now deleted everything and retried deployment, but this time with West Europe as location, and I now have some more services deployed. I also did not get an error when it comes to the `PlatformFaultDomainCount` being 3.

![Skjermbilde 2020-05-28 kl  08 59 33](https://user-images.githubusercontent.com/159861/83109605-f6532d80-a0c1-11ea-8fc5-ba20e3a04d11.png)

As far as I can see, there are no additional types of services. Could the problem with `PlatformFaultDomainCount=3` in Norway East cause the deployment of metanodes not being done? I did not see metanodes in the list of deployments on my first try either

**Comment by lindsve** [comment]
Hmm, I retried the curl command and I'm getting the same error

> {"results":[{"statement_id":0,"error":"meta service unavailable"}]}

**Comment by chobbs** [comment]
@lindsve - looks like we need to update the deployment templates to support regions with 2 or less fault domains. adding for inclusion in next release. In the meantime, below is a table of Azure regions and the number of fault domains supported.

fault domain: https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/managed-disks-common-fault-domain-region-list.md

**Comment by lindsve** [comment]
Any idea when the next release will be?

Alternatively, what is the value of `--plan` when accepting terms before deployment from local clone of this repo:

`az vm image terms accept --publisher influxdata --offer influxdb-enterprise-vm --plan <PLAN_VALUE>`

**Comment by chobbs** [comment]
there are 2 values for  `--plan` that need to be accepted (data|meta) these should be done as part of the deploy.sh script included in the repo.
